version: '3.9'
services:
  # redis:
  #   image: 'redis:alpine'
  #   container_name: redis
  #   restart: unless-stopped
  #   logging:
  #     driver: 'none'
  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   restart: unless-stopped
  #   logging:
  #     driver: 'json-file'
  #     options:
  #       max-size: '50m'
  #       max-file: '5'
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   volumes:
  #     - mongodb:/data/db
  #   ports:
  #     - 27017:27017
  api:
    image: 'ghcr.io/novuhq/novu/api:0.17.1'
    # depends_on:
    #   - mongodb
    #   - redis
    container_name: api
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'
    environment:
      NODE_ENV: ${NOVU_NODE_ENV}
      API_ROOT_URL: ${NOVU_API_ROOT_URL}
      DISABLE_USER_REGISTRATION: ${NOVU_DISABLE_USER_REGISTRATION}
      PORT: ${NOVU_API_PORT}
      FRONT_BASE_URL: ${NOVU_FRONT_BASE_URL}
      MONGO_URL: ${NOVU_MONGO_URL}
      MONGO_MAX_POOL_SIZE: ${NOVU_MONGO_MAX_POOL_SIZE}
      REDIS_HOST: ${NOVU_REDIS_HOST}
      REDIS_PORT: ${NOVU_REDIS_PORT}
      REDIS_PASSWORD: ${NOVU_REDIS_PASSWORD}
      REDIS_DB_INDEX: 2
      REDIS_CACHE_SERVICE_HOST: ${NOVU_REDIS_CACHE_SERVICE_HOST}
      REDIS_CACHE_SERVICE_PORT: ${NOVU_REDIS_CACHE_SERVICE_PORT}
      S3_LOCAL_STACK: ${NOVU_S3_LOCAL_STACK}
      S3_BUCKET_NAME: ${NOVU_S3_BUCKET_NAME}
      S3_REGION: ${NOVU_S3_REGION}
      AWS_ACCESS_KEY_ID: ${NOVU_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${NOVU_AWS_SECRET_ACCESS_KEY}
      JWT_SECRET: ${NOVU_JWT_SECRET}
      STORE_ENCRYPTION_KEY: ${NOVU_STORE_ENCRYPTION_KEY}
      SENTRY_DSN: ${NOVU_SENTRY_DSN}
      NEW_RELIC_APP_NAME: ${NOVU_NEW_RELIC_APP_NAME}
      NEW_RELIC_LICENSE_KEY: ${NOVU_NEW_RELIC_LICENSE_KEY}
      API_CONTEXT_PATH: ${NOVU_API_CONTEXT_PATH}
    ports:
      - '3000:3000'
  worker:
    image: 'ghcr.io/novuhq/novu/worker:0.17.1'
    # depends_on:
    #   - mongodb
    #   - redis
    container_name: worker
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'
    environment:
      NODE_ENV: ${NOVU_NODE_ENV}
      MONGO_URL: ${NOVU_MONGO_URL}
      MONGO_MAX_POOL_SIZE: ${NOVU_MONGO_MAX_POOL_SIZE}
      REDIS_HOST: ${NOVU_REDIS_HOST}
      REDIS_PORT: ${NOVU_REDIS_PORT}
      REDIS_PASSWORD: ${NOVU_REDIS_PASSWORD}
      REDIS_DB_INDEX: 2
      REDIS_CACHE_SERVICE_HOST: ${NOVU_REDIS_CACHE_SERVICE_HOST}
      REDIS_CACHE_SERVICE_PORT: ${NOVU_REDIS_CACHE_SERVICE_PORT}
      S3_LOCAL_STACK: ${NOVU_S3_LOCAL_STACK}
      S3_BUCKET_NAME: ${NOVU_S3_BUCKET_NAME}
      S3_REGION: ${NOVU_S3_REGION}
      AWS_ACCESS_KEY_ID: ${NOVU_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${NOVU_AWS_SECRET_ACCESS_KEY}
      STORE_ENCRYPTION_KEY: ${NOVU_STORE_ENCRYPTION_KEY}
      SENTRY_DSN: ${NOVU_SENTRY_DSN}
      NEW_RELIC_APP_NAME: ${NOVU_NEW_RELIC_APP_NAME}
      NEW_RELIC_LICENSE_KEY: ${NOVU_NEW_RELIC_LICENSE_KEY}
  ws:
    image: 'ghcr.io/novuhq/novu/ws:0.17.1'
    # depends_on:
    #   - mongodb
    #   - redis
    container_name: ws
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'
    environment:
      PORT: ${NOVU_WS_PORT}
      NODE_ENV: ${NOVU_NODE_ENV}
      MONGO_URL: ${NOVU_MONGO_URL}
      MONGO_MAX_POOL_SIZE: ${NOVU_MONGO_MAX_POOL_SIZE}
      REDIS_HOST: ${NOVU_REDIS_HOST}
      REDIS_PORT: ${NOVU_REDIS_PORT}
      REDIS_PASSWORD: ${NOVU_REDIS_PASSWORD}
      JWT_SECRET: ${NOVU_JWT_SECRET}
      WS_CONTEXT_PATH: ${NOVU_WS_CONTEXT_PATH}
    ports:
      - '3002:3002'
  web:
    image: 'ghcr.io/novuhq/novu/web:0.17.1'
    depends_on:
      - api
      - worker
    container_name: web
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'
    environment:
      REACT_APP_API_URL: ${NOVU_API_ROOT_URL}
      REACT_APP_ENVIRONMENT: ${NOVU_NODE_ENV}
      REACT_APP_WIDGET_EMBED_PATH: ${NOVU_WIDGET_EMBED_PATH}
      REACT_APP_DOCKER_HOSTED_ENV: 'true'
      REACT_APP_WS_URL: ${NOVU_REACT_APP_WS_URL}
    ports:
      - 4200:4200
  widget:
    image: 'ghcr.io/novuhq/novu/widget:0.17.1'
    depends_on:
      - api
      - worker
      - web
    container_name: widget
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'
    environment:
      REACT_APP_API_URL: ${NOVU_API_ROOT_URL}
      REACT_APP_WS_URL: ${NOVU_REACT_APP_WS_URL}
      REACT_APP_ENVIRONMENT: ${NOVU_NODE_ENV}
      WIDGET_CONTEXT_PATH: ${NOVU_WIDGET_CONTEXT_PATH}
    ports:
      - 4500:4500
  embed:
    depends_on:
      - widget
    image: 'ghcr.io/novuhq/novu/embed:0.17.1'
    container_name: embed
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'
    environment:
      WIDGET_URL: ${NOVU_WIDGET_URL}
    ports:
      - 4701:4701
volumes:
  mongodb: ~
